Repository Fridge-Chef/FridgeChef_BE, pull requests merged in 2024-11, with the labels that each got.

#209 test : ingredientService(조회, 생성), ingredientController
  src/main/java/Fridge_Chef/team/ingredient/service/IngredientService.java
  src/test/java/Fridge_Chef/team/ingredient/rest/IngredientControllerTest.java
  src/test/java/Fridge_Chef/team/ingredient/service/IngredientServiceTest.java
Labels: ingredient, test

#208 🐛 ♻️ 앱 연동 중 생긴 문제 수정 [레시피]
  .github/workflows/ci.yml
  .github/workflows/tag.yml
  http-api.env.json
  http/comment.http
  http/fridge.http
  http/http-client.env.json
  http/recipe.http
  src/main/java/Fridge_Chef/team/board/domain/Board.java
  src/main/java/Fridge_Chef/team/board/domain/Context.java
  src/main/java/Fridge_Chef/team/board/repository/BookDslRepository.java
  src/main/java/Fridge_Chef/team/board/rest/BoardsController.java
  src/main/java/Fridge_Chef/team/board/service/BoardRecipeService.java
  src/main/java/Fridge_Chef/team/board/service/response/BoardMyRecipeResponse.java
  src/main/java/Fridge_Chef/team/comment/service/CommentService.java
  src/main/java/Fridge_Chef/team/config/dev/SecurityDevConfig.java
  src/main/java/Fridge_Chef/team/config/prod/SecurityConfig.java
  src/main/java/Fridge_Chef/team/exception/ErrorCode.java
  src/main/java/Fridge_Chef/team/fridge/domain/Fridge.java
  src/main/java/Fridge_Chef/team/fridge/domain/FridgeIngredient.java
  src/main/java/Fridge_Chef/team/fridge/rest/FridgeController.java
  src/main/java/Fridge_Chef/team/fridge/rest/request/FridgeIngredientRequest.java
  src/main/java/Fridge_Chef/team/fridge/rest/response/FridgeIngredientResponse.java
  src/main/java/Fridge_Chef/team/fridge/service/FridgeService.java
  src/main/java/Fridge_Chef/team/image/service/ImageProdService.java
  src/main/java/Fridge_Chef/team/ingredient/domain/IngredientCategory.java
  src/main/java/Fridge_Chef/team/ingredient/service/IngredientService.java
  src/main/java/Fridge_Chef/team/purch/coupang/CouPangManager.java
  src/main/java/Fridge_Chef/team/purch/naver/NaverManager.java
  src/main/java/Fridge_Chef/team/purch/rest/PurchController.java
  src/main/java/Fridge_Chef/team/purch/service/PurchService.java
  src/main/java/Fridge_Chef/team/purch/service/response/PurchResponse.java
  src/main/java/Fridge_Chef/team/recipe/domain/Difficult.java
  src/main/java/Fridge_Chef/team/recipe/domain/Recipe.java
  src/main/java/Fridge_Chef/team/recipe/dump/BasicRecipesInitializer.java
  src/main/java/Fridge_Chef/team/recipe/repository/RecipeDslRepository.java
  src/main/java/Fridge_Chef/team/recipe/rest/RecipeController.java
  src/main/java/Fridge_Chef/team/recipe/rest/response/RecipeSearchResponse.java
  src/main/java/Fridge_Chef/team/recipe/service/RecipeService.java
  src/main/java/Fridge_Chef/team/security/service/CustomOAuth2UserService.java
  src/main/java/Fridge_Chef/team/user/rest/model/AuthenticatedUser.java
  src/main/resources/application/jpa.yml
  src/test/java/Fridge_Chef/team/board/rest/BoardControllerTest.java
  src/test/java/Fridge_Chef/team/board/service/BorderServiceTest.java
Labels: 레시피

#224 🪶 무중단 배포 방식 적용.
  .github/workflows/cicd.yml
  src/main/java/Fridge_Chef/team/config/dev/SecurityDevConfig.java
  src/main/java/Fridge_Chef/team/config/prod/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ci/cd, build
